% TaskDefinition Helper File
%
% TD: TaskDefinition, a struct variable
%
% --- Trial definitions
%   Currently ORCA requires all trials in a session to be homogeneous.
% TD.Trial.Duration
% TD.Trial.Baseline
% TD.Trial.Interest
% TD.Trial.Stimulus(x)        % Start, End
% 
% --- Session definitions
% TD.Session.Date             % datetime variable
% TD.Session.Name             % chars
% TD.Session.Path             % folder 
% TD.Session.RawFile          %
% TD.Session.Timestamps       % 
% TD.Session.Stimuli{x}       % 
% TD.Session.Masks.[Method]   % Mask Files generated by various methods
%
% --- Stimuli definitions
% TD.Stimuli(x).
% TD.Stimuli(x).Name
% TD.Stimuli(x).Description
% TD.Stimuli(x).Type          % Sound? Light? Shock? Opto?
% TD.Stimuli(x).Parametres
% TD.Stimuli(x).ValueExplains