function status = ThorlabsWriteSLM(template, choice)
%ThorlabsWriteSLM Generate XML file for SLM
%   ANOTHER DEVICE-SPECIFIC CODE

global ORCA

ORCA.Online.ThorlabsWriteSLM.FilePosition = 'C:\Users\user\Documents\ThorImageLS 4.1\Capture Templates\Active.xml';

findSLM = @(x) strcmp(x, 'SLM');
s = xml2struct( ORCA.Device.SLMFilePosition );
slmidx = cellfun(findSLM, {s.Children(:).Name});

if choice == 0
    % clear SLM and make it a clean xml file
    s.Children(slmidx).Children = struct(...
        'Name', '#text', ...
        'Attributes', [], ...
        'Data','     ', ...
        'Children', [] ...
    );

elseif choice>0
    roi = regionprops(template == choice, 'Centroid','MajorAxisLength');
    roi.MajorAxisLength = roi.MajorAxisLength/2;
    ORCA.Device.ZoomUmPixel 
    % select one roi in mask, calculate its x-y-radius, and write XML
    s.Children(slmidx).Children(2) = struct(...
        'Name', 'Pattern', ...
        'Attributes', struct(...
            'blue',             '0', ...
            'durationMS',       '100',  ...
            'fileID',           '1', ...
            'green',            '255', ...
            'name',             sprintf('SLMPattern_%3d', choice), ...
            'pixelSizeUM',      sprintf('%.3f', ORCA.Experiment.Imaging.PixelSizeum), ...
            'postIteIdleMS',    '0', ...
            'postPatIdleMS',    '0', ...
            'iterations',       '10', ...
            'measurePowerMW',   '0', ...
            'measurePowerMWPerUM2','0', ...
            'power',            '100',...
            'preIteIdleMS',     '0',...
            'prePatIdleMS',     '0',...
            'pxSpacing',        '1',...
            'red',              '255',...
            'roiHeightUM',      '17.07',...
            'roiWidthUM',       '14.84',...
            'shape',            'Ellipse',...
            'xOffsetUM',        '209.41',...
            'yOffsetUM',        '209.41'), ...            
        'Data','     ', ...
        'Children', []);

struct2xml( s, ORCA.Device.SLMFilePosition )
end

