function shifts = load_shifts_TurboReg(filepath)
%LOAD_SHIFTS_TURBOREG load shift data generated by TurboReg
%   SHIFTS = LOAD_SHIFTS_TURBOREG(FILEPATH) loads the txt file FILEPATH, and all numbers 
%   within the file. SHIFTS returns [nframes * 2] matrix, each row (yshift, xshift).
%
%   See also FOPEN.

%   Weihao Sheng, 2020-04-26
%   Yang Yang's Lab of Neural Basis of Learning and Memory
%   School of Life Sciences and Technology, ShanghaiTech University,
%   Shanghai, China


fid  = fopen(filepath,'r');
if fid < 2, shifts = []; return; end

loadshifts = fscanf(fid,'%f');
loadshifts = permute(reshape(loadshifts, [4,length(loadshifts)/4]), [2 1]);
fclose(fid);

shifts(:,1) = loadshifts(:,4)-loadshifts(:,2);  % shift y
shifts(:,2) = loadshifts(:,3)-loadshifts(:,1);  % shift x
end

